### ISSUE TITLE
People individial pages are showing error after upgrade to 974b8c02f4

### ISSUE THREAD

**Issue by nishad** [BibApp/BibApp#103]
After Upgrade to latest Github version (974b8c02f4), BibApp throws an error while visiting people pages. 

``` ruby
ActionView::Template::Error (undefined method `shared_works_url' for #<#<Class:0x5a63b50>:0x5a00348>):
    9:         .person-image-wrapper
    10:           = link_to(image_tag(image_url, :size => "56x74", :alt => last_name, :title => last_name, :class => "person-image"), person_path(id))
    11:           .person-coauthor-link
    12:             = link_to fugue_icon_tag('users', :alt => t('people.co_authors_list.shared_works'), :title => t('people.co_authors_list.shared_works')), shared_works_url(:people => [@person.id, id])
    13:         .person-image-metadata
    14:           %strong #{ p.value}
    15:         .person-last-name.left
  app/views/shared/_coauthors_list.html.haml:12:in `_app_views_shared__coauthors_list_html_haml___1928245431_47224560_12633900'
  app/views/shared/_coauthors_list.html.haml:3:in `each'
  app/views/shared/_coauthors_list.html.haml:3:in `_app_views_shared__coauthors_list_html_haml___1928245431_47224560_12633900'
  app/views/shared/_coauthors.html.haml:10:in `_app_views_shared__coauthors_html_haml__2038156952_47277300_3718430'
  app/views/people/show.html.haml:34:in `_app_views_people_show_html_haml__1239929134_47372280_0'
```

**Comment by hading** [comment]
I'm unable to replicate this. shared_works_url is a method that is automatically generated by rails because of the code in config/routes.rb:

```
resources :works do
  collection do
    get :orphans
    delete :destroy_multiple
    post :orphans_delete
    get :shared
  end
  member do
    get :add_to_saved
    get :remove_from_saved
    put :change_type
  end
```

The line

get :shared

should be causing rails to generate this method. Is your config/routes.rb as above? If you do rake routes | grep shared in your rails directory do you get:

```
                      shared_works GET    /works/shared(.:format)                                {:controller=>"works", :action=>"shared"}
```
